@startuml
left to right direction

actor recorder
actor audiodownloader
actor database

rectangle system {
usecase downloadAudio
usecase registryAudio
usecase addMetaData
usecase getMetaData
usecase searchAudio
usecase writeData
usecase readData
}

recorder --> registryAudio
registryAudio .> writeData : <<included>>

audiodownloader --> downloadAudio
downloadAudio .> readData : <<included>>

writeData --> database
readData --> database

addMetaData .> registryAudio : <<extended>>
getMetaData .> downloadAudio : <<extended>>
recorder --> searchAudio
audiodownloader --> searchAudio
getMetaData .> searchAudio : <<extended>>

@enduml