@startuml
left to right direction

actor AuthorizedUser as recorder
actor AudioDownloader as audiodownloader
actor Storage as storage

rectangle "audio storage manager system" {
usecase downloadAudio
usecase registryAudio
usecase addMetaData
usecase getMetaData
usecase searchAudio
usecase writeData
usecase readData
usecase login
usecase authorization
}

recorder --> registryAudio
registryAudio .> writeData : <<extened>>
registryAudio .> login : <<included>>

audiodownloader --> downloadAudio
downloadAudio .> readData : <<included>>
downloadAudio .> authorization : <<included>>

readData --> storage

addMetaData .> registryAudio : <<extended>>
getMetaData .> downloadAudio : <<extended>>
recorder --> searchAudio
audiodownloader --> searchAudio
searchAudio .> authorization : <<included>>
getMetaData .> searchAudio : <<extended>>

@enduml